def ayuda():
    print("Estos son tus comandos: \n")
    print("'linea''coordenada x''coordenada x fin''coordenada y''coordenada y fin' te va a generar una linea")
    print("'color list' es para ver todos los colores")
    print("'color set' 'NOMBRE' cambio el color de la linea")
    print("'fondo''NOMBRE'cambia el color del fondo")
    print("'triangulo''coordenada x1''coordenada y1 fin''coordenada x2''coordenada y2''coordenada x3''coordenada y3'")
    print("cuadrado'x'y''lado' poniendo estas coordenadas se crea el cuadrado")
    print("circulo 'centro_x' 'centro_y' 'radio' con estas coordenadas se crea nuesto cisculo")
    print("rectagulo 'x''y''ancho''alto'con este se crea un rectangulo")